### ISSUE TITLE
Exception version Qt_5 not defined in file libQt5Qml.so.5

### ISSUE THREAD

**Issue by TheSuunny** [qmlnet/qmlnet#126]
Hi, I cleaned folder .nuget yesterday, and now I’m catching an exception, although everything worked before that, what could be the problem? All these files are in the folder, and qt5-base is also installed.

OS: Arch Linux

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Qml.Net.Internal.Interop' threw an exception. ---> System.Exception: Library could not be loaded: /home/sunny/.nuget/packages/qml.net.linuxbinaries/0.10.0/runtimes/linux-x64/native/libQmlNet.so: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm version Qt_5 not defined in file libQt5Qml.so.5 with link time reference: /home/sunny/.nuget/packages/qml.net.linuxbinaries/0.10.0/runtimes/linux-x64/native/libQmlNet.so
   at NetNativeLibLoader.Loader.UnixPlatformLoader.LoadLibrary(String path, SymbolFlag flags)
   at Qml.Net.Internal.Interop..cctor()
   --- End of inner exception stack trace ---
   at Qml.Net.QQuickStyle.SetStyle(String style)
   at Yove.Discord.Program.Main(String[] args) in /home/sunny/Documents/Yove.Discord/Program.cs:line 9
```

**Comment by pauldotknopf** [comment]
Try adding ```RuntimeManager.DiscoverOrDownloadSuitableQtRuntime();``` in your ```Program.Main()```.

**Comment by TheSuunny** [comment]
Oh, yes, thank you very much for your work :)

**Comment by pauldotknopf** [comment]
You are very welcome ;)

**Comment by pauldotknopf** [comment]
What are you building? A Discord client?

**Comment by TheSuunny** [comment]
No, there are already a lot of good libraries for a discord on .net, I make for myself all sorts of small utilities :)
