### ISSUE TITLE
How to invoke C++ method?

### ISSUE THREAD

**Issue by vadi2** [qmlnet/qmlnet#138]
I see that it's possible to invoke a C++ method from the readme, but I can't get it working. My example:

```js
// QML
TextArea {
  id: textArea
  Component.onCompleted: dotnet.invokeCpp(textArea)
}

// C#
    public void InvokeCpp(dynamic qQuickTextDocument)
    {
      var qTextDocument = qQuickTextDocument.textDocument();
    }
```

It just bombs out with:

```
Exception has occurred: CLR/System.Exception
An unhandled exception of type 'System.Exception' occurred in Qml.Net.dll: 'Invoking method failed.'
   at Qml.Net.Internal.Qml.NetQObject.InvokeMethod(String methodName, NetVariantList parameters)
   at Qml.Net.Internal.Qml.NetQObject.NetQObjectDynamic.InvokeMethod(String methodName, Object[] parameters)
   at Qml.Net.Internal.Qml.NetQObject.NetQObjectDynamic.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Program.NetObject.InvokeCpp(Object qQuickTextDocument) in /home/vadi/Programs/Hammer/Program.cs:line 156
```

I've verified that I am indeed passing in a `QQuickTextDocument` class which has a `QTextDocument * textDocument() const` method.

**Comment by vadi2** [comment]
I've tried a whole lot of things involving `InvokeMethod` but nothing is working.

**Comment by iWeaverMan** [comment]
Method textDocument() is not invokable
https://stackoverflow.com/questions/24642370/qmetaobjectinvokemethod-no-such-method-when-using-inheritance/24642620

**Comment by vadi2** [comment]
Oh. So Qml.Net can't actually invoke any method? What can I do then - do I have to provide some C++ glue myself?

**Comment by pauldotknopf** [comment]
You'd have to provide C++ glue yourself.

You can only invoke things that are known to the Qt meta system.

**Comment by pauldotknopf** [comment]
Update, you can interact with ```QObject`` types now using ```INetQObject```.
