### ISSUE TITLE
Doesn't work properly with .NET Framework/Mono 

### ISSUE THREAD

**Issue by FieryRider** [qmlnet/qmlnet#207]
This is not the same issue as #76 though it's probably related.

- It doesn't want to run in projects using the old `packages.config`. When ran from those type of projects it results in exception:
    ```Unhandled Exception: System.TypeInitializationException: The type initializer for 'Qml.Net.Internal.Interop' threw an exception. ---> System.Exception: Unable to find the native Qml.Net library. Try calling "RuntimeManager.DiscoverOrDownloadSuitableQtRuntime();" in Program.Main()
   at Qml.Net.Internal.Interop..cctor()
   --- End of inner exception stack trace ---
   at Qml.Net.Internal.Interop.get_QQuickStyle()
   at Qml.Net.QQuickStyle.SetStyle(String style)
   at QmlTestNF.Program.Main(String[] args) in D:\@UserFolder@\Documents\code\C#\QmlTestNF\QmlTestNF\Program.cs:line 17
 If converted to PackageReference there is no longer exception.
- When run with PackageReference everything seems to work fine (if we ignore the following error `QWindowsContext: OleInitialize() failed:  "COM error 0xffffffff80010106 RPC_E_CHANGED_MODE (Unknown error 0x080010106)`), the app loads, the custom (C#) components load until you try to access something in a custom (C#) component. Then it results in the following exception:
    ```Unhandled Exception: System.TypeAccessException: Attempt by method 'DynamicClass.method(Qml.Net.Internal.Types.NetReference, Qml.Net.Internal.Qml.NetVariantList, Qml.Net.Internal.Qml.NetVariant, System.Threading.Tasks.Task ByRef)' to access type 'Qml.Net.Internal.Types.NetReference' failed.
   at method(NetReference , NetVariantList , NetVariant , Task& )
   at Qml.Net.Internal.DefaultCallbacks.InvokeMethod(IntPtr m, IntPtr t, IntPtr p, IntPtr r)
   at QmlTestNF.Program.Main(String[] args) in D:\@UserFolder@\Documents\code\C#\QmlTestNF\QmlTestNF\Program.cs:line 17
    QQmlComponent: Component destroyed while completion pending

This is my code (if you remove `mainController.print()` it works fine):
Program.cs

```c#
using Qml.Net;
using Qml.Net.Runtimes;

namespace QmlTestNF {
    class Program {
        static int Main(string[] args) {
            RuntimeManager.DiscoverOrDownloadSuitableQtRuntime();
            QQuickStyle.SetStyle("Material");
            using (var application = new QGuiApplication()) {
                using (var qmlEngine = new QQmlApplicationEngine()) {
                    Qml.Net.Qml.RegisterType<MainController>("Extends");
                    qmlEngine.Load("Main.qml");
                    
                    return application.Exec();
                }
            }
        }
    }
}
```

MainController.cs

```c#
using System;
namespace QmlTestNF {
    class MainController {
        public void Print() {
            Console.WriteLine("Something");
        }
    }
}
```
Main.qml

```qml
import QtQuick 2.12
import QtQuick.Layouts 1.3
import QtQuick.Controls 2.12
import QtQuick.Controls.Material 2.12
import Extends 1.0

ApplicationWindow {
    id: window
    width: 1366
    height: 768
    visible: true
    title: "DMTViewer"

    Material.theme: Material.Dark
    Material.primary: Material.Grey
    Material.accent: Material.Green

    MainController {
        id: mainController
        Component.onCompleted: {
            console.log("loaded")
            mainController.print()
        }
    }    
}
```

**Comment by pauldotknopf** [comment]
It works for me on Linux (not helpful, I know).

![image](https://user-images.githubusercontent.com/523150/83346893-8c6b9b80-a2ee-11ea-8a44-08fb1103ebdb.png)


Let me try on Windows in a bit.

**Comment by FieryRider** [comment]
On linux it runs under .Net Core doesn't it? I don't have problems with .Net Core on Linux nor or Windows. But .NetFramework is problematic

**Comment by pauldotknopf** [comment]
What does your csproj look like? Share a repro repo?

**Comment by FieryRider** [comment]
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{48C7908B-16FA-4FDF-8159-39C935E2F09E}</ProjectGuid>
    <OutputType>Exe</OutputType>
    <RootNamespace>QmlTestNF</RootNamespace>
    <AssemblyName>QmlTestNF</AssemblyName>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\x64\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugType>full</DebugType>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>7.3</LangVersion>
    <ErrorReport>prompt</ErrorReport>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <Prefer32Bit>true</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin\x64\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
    <DebugType>pdbonly</DebugType>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>7.3</LangVersion>
    <ErrorReport>prompt</ErrorReport>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <Prefer32Bit>true</Prefer32Bit>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="MainController.cs" />
    <Compile Include="Program.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Qml.Net">
      <Version>0.10.1</Version>
    </PackageReference>
    <PackageReference Include="Qml.Net.WindowsBinaries">
      <Version>0.10.1</Version>
    </PackageReference>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

**Comment by pauldotknopf** [comment]
Ok, it looks like it's loading the native libs correctly.

I'd like to see the actual exception. Is it a .NET exception? Or a native segfault? My Windows machine with me right now, it would help a lot of you could compile QmlNet yourself (at 0.10.1), so that I can get a full stacktrace.

**Comment by FieryRider** [comment]
Will you compile it from the code of the repo or should I compile QmlNet?

**Comment by pauldotknopf** [comment]
Erggh, it looks like it's the dynamic IL that's being generated doesn't plan nice with .NET Framework.

**Comment by pauldotknopf** [comment]
```
: 'Attempt by method 'DynamicClass.method(Qml.Net.Internal.Types.NetReference, Qml.Net.Internal.Qml.NetVariantList, Qml.Net.Internal.Qml.NetVariant, System.Threading.Tasks.Task ByRef)' to access type 'Qml.Net.Internal.Types.NetReference' failed.'
```

**Comment by pauldotknopf** [comment]
I'm pushing an alpha nuget package soon, I'll ping you when it is up.

**Comment by pauldotknopf** [comment]
[Pushed](https://www.nuget.org/packages/Qml.Net/0.11.0-alpha.78).

**Comment by FieryRider** [comment]
This can be reopened. It works not calling void C# functions but calling functions that return result throws exception again. Updated the [repro repo](https://github.com/FieryRider/TestRepo1) with the new test case.
