### ISSUE TITLE
Building on Linux fails

### ISSUE THREAD

**Issue by bitsmaker** [qmlnet/qmlnet#209]
Hello,

When I tried to build on Ubuntu 18.04 I get the following error

> Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-gitversion does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
Unhandled exception. SimpleExec.NonZeroExitCodeException: The command exited with code 1.
   at SimpleExec.ProcessExtensions.Throw(Process process)
   at SimpleExec.Command.Read(String name, String args, String workingDirectory, Boolean noEcho, String windowsName, String windowsArgs, String echoPrefix, Action`1 configureEnvironment)
   at Build.Buildary.Shell.ReadShell(String shell) in /home/mmahimtura/qmlnet/build/scripts/Buildary/Shell.cs:line 52
   at Build.Buildary.GitVersion.GetGitVersion(String directory) in /home/mmahimtura/qmlnet/build/scripts/Buildary/GitVersion.cs:line 15
   at Build.Program.Main(String[] args) in /home/mmahimtura/qmlnet/build/scripts/Program.cs:line 27

I would appreciate any help

Thanks

**Comment by shartte** [comment]
Hi, can you explain how exactly you are building? Are you using the build.sh shell script?
Oh, and which version of dotnet do you have installed?

**Comment by bitsmaker** [comment]
I am using the build.sh and using dotnet version 3.1

**Comment by shartte** [comment]
Can you please try the following?

```
dotnet tool install -g GitVersion.Tool --version 5.3.4
export PATH="$PATH:$HOME/.dotnet/tools"
```

**Comment by bitsmaker** [comment]
I did do the tool install, did not know I had to also export the PATH. It got further after I did that but still getting errors
I have qt installed

Version: {"Version":"0.11.0","VersionMajor":0,"VersionMinor":11,"VersionPatch":0,"PreReleaseLabel":"alpha","PreReleaseTag":"alpha.78","PreReleaseNumber":"78","FullVersion":"0.11.0-alpha.78","AssemblySemVer":"0.11.0.0"}
Build: Starting... (default)
Build: clean: Starting...
Build: clean: Succeeded. (2.8 ms)
Build: build-native: Starting...
qmake: could not find a Qt installation of ''
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
Build: build-native: SimpleExec.NonZeroExitCodeException: The command exited with code 2.
   at SimpleExec.ProcessExtensions.Throw(Process process)
   at SimpleExec.Command.Run(String name, String args, String workingDirectory, Boolean noEcho, String windowsName, String windowsArgs, String echoPrefix, Action`1 configureEnvironment)
   at Build.Buildary.Shell.RunShell(String shell) in /home/mmahimtura/qmlnet/build/scripts/Buildary/Shell.cs:line 25
   at Build.Program.<>c.<Main>b__0_2() in /home/mmahimtura/qmlnet/build/scripts/Program.cs:line 65
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Bullseye.Internal.ActionTarget.RunAsync(Boolean dryRun, Boolean parallel, Logger log, Func`2 messageOnly)
Build: build-native: Failed! The command exited with code 2. (50 ms)
Build: ─────────────────────────────────────
Build: Duration      Outcome    Target      
Build: ────────────  ─────────  ────────────
Build: 3 ms   5.3%   Succeeded  clean       
Build: 50 ms  94.7%  Failed!    build-native
Build: ─────────────────────────────────────
Build: Failed! (default) (62.1 ms)

**Comment by bitsmaker** [comment]
Thanks for your help, I was able to resolve this issue
